# Generated by Django 5.2 on 2025-04-29 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('categoria', models.CharField(blank=True, max_length=100, null=True)),
                ('marca', models.CharField(blank=True, max_length=100, null=True)),
                ('imagenPrincipal', models.ImageField(upload_to='productos/')),
                ('imagenSecundaria1', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('imagenSecundaria2', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('caracteristicas', models.TextField(blank=True, help_text='Separar cada característica con un salto de línea', null=True)),
                ('ficha_tecnica', models.FileField(blank=True, null=True, upload_to='fichas/')),
            ],
        ),
    ]
