# Generated by Django 5.2 on 2025-05-03 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferremas_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
