# Generated by Django 5.2 on 2025-05-15 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferremas_page', '0003_mensajecontacto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='stock',
            field=models.PositiveIntegerField(default=0, help_text='Cantidad disponible en inventario'),
        ),
    ]
