# Generated by Django 5.2 on 2025-05-16 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferremas_page', '0005_compra_compraitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='email',
            field=models.EmailField(default='correo@ejemplo.com', max_length=254),
            preserve_default=False,
        ),
    ]
